name: GuardDog

on:
  pull_request:
    branches:
      - main
      - v*

permissions:
  contents: read

jobs:
  guarddog:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan new dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install GuardDog
        run: pip install guarddog

      - name: Identify updated or new dependencies
        run: |
          diff --changed-group-format='%>' --unchanged-group-format='' <(git show "origin/${GITHUB_BASE_REF}:requirements.txt") requirements.txt > new-dependencies.txt || true
          cat new-dependencies.txt

      - run: guarddog pypi verify new-dependencies.txt --output-format sarif --exclude-rules repository_integrity_mismatch > guarddog.sarif

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: guarddog-builtin
          sarif_file: guarddog.sarif


